# animation-1
- domain_lora_scale: 1.0
  adapter_lora_path: "models/Motion_Module/v3_sd15_adapter.ckpt"
  dreambooth_path:   "models/DreamBooth_LoRA/realisticVisionV51_v51VAE.safetensors"

  inference_config: "configs/inference/inference-v3.yaml"
  motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
  controlnet_path:   "models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt"

  seed: -1
  steps: 50
  guidance_scale: 8.5

  controlnet_image_indexs: [0]
  controlnet_images: "/scratch/trv3px/video_detection/AnimateDiff/unsafe_dataset"

  file_path: "prompts/unsafe.txt"
  n_prompt:
    - "worst quality, low quality, letterboxed"

  save_predx_0: "./predx_0/unsafe.pt"
  
  save_predx_t: "./predx_t/unsafe.pt"


# # animation-2
# - domain_lora_scale: 1.0
#   adapter_lora_path: "models/Motion_Module/v3_sd15_adapter.ckpt"
#   dreambooth_path:   "models/DreamBooth_LoRA/realisticVisionV51_v51VAE.safetensors"

#   inference_config: "configs/inference/inference-v3.yaml"
#   motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"

#   controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
#   controlnet_path:   "models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt"

#   seed: -1
#   steps: 25
#   guidance_scale: 8.5

#   controlnet_image_indexs: [0]
#   controlnet_images:
#     - "__assets__/demos/image/RealisticVision_sunset.png"

#   prompt:
#     - "masterpiece, bestquality, highlydetailed, ultradetailed, sunset, orange sky, warm lighting, fishing boats, ocean waves, seagulls, rippling water, wharf, silhouette, serene atmosphere, dusk, evening glow, golden hour, coastal landscape, seaside scenery"
#     - "masterpiece, bestquality, highlydetailed, ultradetailed, sunset, orange sky, warm lighting, fishing boats, ocean waves, seagulls, rippling water, wharf, silhouette, serene atmosphere, dusk, evening glow, golden hour, coastal landscape, seaside scenery"
#   n_prompt:
#     - "worst quality, low quality, letterboxed"
